name: NMLShields
version: '1.0'
main: io.github.NoOne.nMLShields.NMLShields
api-version: '1.21'
depend:
  - NMLItems
  - NMLPlayerStats
softdepend:
  - DamagePlugin
commands:
  generateShield:
    description: Generates a random shield
    usage: /<command> <level> <rarity>